name: dram_db_bindings
description: Dart bindings used to communicate with the backend database
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

#dev_dependencies: