name: dram
description: Dart package that contains a set of common utilities.
version: 2.0.1
homepage: https://github.com/TomasWeg/dram

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  firebase_crashlytics: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: