name: dram_queryable
description: Contains a generic way to query data.
version: 1.0.0
repository: https://github.com/TomasWeg/dram
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.9.1 <2.0.0"

dependencies:
  dram_core: ^1.0.0
  sqflite: ^2.0.0+3

dependency_overrides:
  dram_core:
    path: ../dram_core/

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  flutter:
    sdk: flutter
