name: dram_core
description: Contains core functionalities to share across dram packages
version: 1.0.0
repository: https://github.com/TomasWeg/dram
issue_tracker: https://github.com/TomasWeg/dram/issues
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
